### ISSUE TITLE
Colours don't display with Elm 0.17

### ISSUE THREAD

**Issue by ccapndave** [philopon/gulp-elm#10]
With the new alpha of Elm 0.17 all the error messages produced by `gulp-elm` are in red, instead of in pretty colours like before.

**Comment by abadi199** [comment]
I don't think this plugin ever show ansi color for the error message for me.
Regardless, I've updated the plugin to shows ansi color in this PR #11. I've tested on both elm 0.16 and 0.17, and it's working for me. Let me know if it works for you too.

**Comment by ccapndave** [comment]
Yes, this works great!  Thanks a lot :)
