### ISSUE TITLE
Elm output mixes with gulp output

### ISSUE THREAD

**Issue by bdukes** [philopon/gulp-elm#12]
The recent change to pipe the `elm-make` output to `stdout` directly means that the output from `elm-make` is mixing with the output from gulp (or other `elm-make` processes), making the output unreadable when multiple processes are generating output, e.g.

```
Potential problems could be:
  * M[i15:39:47s] spelled tFinished 'hjs:LandoCalrissian-modulee' after  12 sm
odul[e15:39:47 ] nStarting 'aLandoCalrissian-modulem'...
e[
15:39:47  ] *Finished ' LandoCalrissian-moduleN' after e33 μse
d to add a source directory or new dependency to elm-package.json
I cannot find module 'Effects'.
```

**Comment by epeterson320** [comment]
This presents problems for error handling too. I had a gulp-watch task to pipe compiler error messages into index.html. Now if there are errors, index.html just says "Compile Error" with no further messages, and I have to open up the terminal and look through the gulp stuff to find and fix my Elm errors.

**Comment by abadi199** [comment]
I think the better way to handle this is to make change in `elm-make` to force using ansi color via an argument (e.g.: `elm-make --force-color`). That way we can still pipe the error message into a buffer and still maintain the ansi color, and possibly adding an options to toggle the color on/off on gulp-elm for use like like @epeterson320 mentioned above. 

In the meantime, I think I'm just gonna revert back to the old way of printing error message by default, and add an options to allow direct printing to `stdout`

**Comment by ItamarGronich** [comment]
So what does this mean? we have to use an older version of gulp-elm until this is fixed? what's the latest version that doesn't act this way?

**Comment by abadi199** [comment]
I reverted back the compiler error message to the non colored version on v0.6.1.

**Comment by hbaughman** [comment]
This [elm make issue](https://github.com/elm-lang/elm-make/issues/123) is where the status of this feature is being tracked.
