### ISSUE TITLE
Add option to specify output file

### ISSUE THREAD

**Issue by alexspurling** [philopon/gulp-elm#16]
Right now the output file will be the same as the source .elm file specified with either the extension ".js" or ".html" depending on what you specify for the filetype option. This means that you cannot specify a different file name or just create a lower case filename which is standard for js and html files.

I believe it would make more sense to reflect the options provided by elm make itself and provide an output parameter that defines the output filename and type.

**Comment by bdukes** [comment]
At the moment we're using [`gulp-rename`](https://www.npmjs.com/package/gulp-rename) to deal with the name.  I think that's a more robust solution, since specifying an output file name won't work if there are multiple input files.  Does that make sense to you?

**Comment by alexspurling** [comment]
As far as I understand, Elm make can only ever have one output file. Any multiple input files will be compiled into a single output .js or .html. Maybe that assumption is incorrect?

**Comment by bdukes** [comment]
That is correct, but the way that `gulp-elm` works is that each input file will fire off its own instance of `elm-make`.  If you _want_ multiple files to be compiled together, you can use [`gulp-elm`'s `bundle` function](https://github.com/philopon/gulp-elm#elmbundleoutput-options), which _does_ require you to specify an output file name.

If you examine [the example in the readme](https://github.com/philopon/gulp-elm#example), when the `src/` directory contains multiple matching files (e.g. `One.elm` and `Two.elm`), the `elm` task will generate `dist/One.js` and `dist/Two.js`, and the `elm-bundle` task will generate `dist/bundle.js`.

Let us know if that sounds like it works for you, if you have any suggestions to how the package works or how to clarify the documentation.  Hope it helps!
