### ISSUE TITLE
Should support --debug mode

### ISSUE THREAD

**Issue by simonh1000** [philopon/gulp-elm#18]
New feature from 0.18. Hope you can add it soon

**Comment by Namek** [comment]
If anyone needed this feature quickly with `gulp-elm` then simply edit `index.js` file by replacing `defaultArgs   = ['--yes']` with `defaultArgs   = ['--yes', '--debug']`

**Comment by abadi199** [comment]
I just released v0.6.0 that adds `--debug` options. https://github.com/philopon/gulp-elm/commit/fce333aec1d359aa0499c2efc372996a8546b9c2
