### ISSUE TITLE
elm-package.json must exist in root directory

### ISSUE THREAD

**Issue by CMoncur** [philopon/gulp-elm#23]
We're embedding a small Elm application into our existing React app, and are using gulp-elm for compilation.  We noticed that the elm-package.json file must exist in the root directory of the repo, even if the Elm application itself is nested within a few directories.

It would be great to have an option to specify a custom path to elm-package.json, or simply to look for elm-package.json in the same directory that the entry point to the Elm app exists.

EDIT: Can use Gulp's `cwd` flag to specify current working directory for elm task.
i.e.
```coffee
gulp.task 'elm-compile-dev', ['elm-init'], ->
  gulp.src config.src, { cwd: 'client/app/public/elm/elm' }
  .pipe(elm({debug: true}))
		.on('error', _onErr)
  .pipe(gulp.dest(config.dest))
  .pipe(browserSync.reload({stream : true}))
```

**Comment by bdukes** [comment]
👍

**Comment by CMoncur** [comment]
In regards to my previous solution, is there a way to pass `cwd` to `elm.init`? It seems like the two tasks are becoming out of sync because the working directories are different, and therefore causing `elm.init` to fail to locate `elm-package.json`.  

Using `process.chdir` is a no-go, because it will conflict with other processes down the line.

Any insight greatly appreciated!

**Comment by bdukes** [comment]
that makes sense, we'll need to add an option to specify the path to `elm-package.json`

**Comment by senterright** [comment]
Hi, I've posted a question about the functionality of gulp-elm and whether or not elm-package.json and elm-stuff can be kept inside nested directories. Here's the stackoverflow question.

http://stackoverflow.com/questions/43840716/is-there-a-way-to-stop-elm-init-in-gulp-elm-from-moving-elm-stuff-and-elm-pack

Thanks!
