### ISSUE TITLE
Allow passing in `warn` as an option

### ISSUE THREAD

**Issue by jackfranklin** [philopon/gulp-elm#7]
Is there any interest in this, such that you get warnings as well as errors when compiling? I'm happy to make the PR.

**Comment by bdukes** [comment]
I would love this to be implemented (i.e. for #8 to be merged)

**Comment by bdukes** [comment]
This has been implemented via #8 (e2e13fe2b745f8db279e884e40055487d1b4d3d1 and b439a5ac56cbd225a2a836db4deb0edc53d3700c)
